### ISSUE TITLE
Not fully logging in with 2FA?

### ISSUE THREAD

**Issue by JourneyOver** [maximousblk/claim-epic-freebies#1] opened 2020-06-17 21:41 UTC
Forked and tried setting this up several different times, every single time it logs in but does not seem to go past the 2FA portion (or I'm completely missing something*).

![6th2dYH](https://user-images.githubusercontent.com/13910285/84953015-6f89e300-b0b8-11ea-9843-296d9a04a28e.png)

I have the `SECRETKEY` with my Authenticator Key in my secrets, so I'm at a loss on why it does not get past this section and fully login and try to claim the games (even though it doesn't seem to fail the action since it continues on to the `post setup repo` bit.

* like it no longer reporting info on logging in or trying to claim the game..

**Comment by maximousblk** [comment] 2020-06-17 21:49
The problem is that the 2FA authentication is a bit sketchy. You should try it locally and if it fails there too, you have to discuss it on the [main repo](https://github.com/Revadike/epicgames-freebies-claimer).

Meanwhile, you can have it running by disabling 2FA on your account temporarily until the problem is fixed.

**Comment by JourneyOver** [comment] 2020-06-17 22:03
Yea seems to be an issue even with just running it locally, as it gets to the 2FA portion and then it just sits there until I manually input a 2FA code.

and I thought that epic made it required to have 2FA enabled on your account now to claim free games or is this no longer a thing?

**Comment by maximousblk** [comment] 2020-06-17 22:10
It still requires 2FA to claim free games.

What this script does is if 2FA login is disabled on your account, it enables it after logging in and disables it after purchase.

But I don't really know what it does when you already have 2FA login enabled.

So I prefer you go for a strong password paired with best practices instead of 2FA if you want to use this.

**Comment by maximousblk** [comment] 2020-06-17 22:20
@JourneyOver I tried to recreate your situation and I think you misspelt the secret name. Or somehow the value of the secret is not passing on.

**Comment by JourneyOver** [comment] 2020-06-17 22:25
I don't think that's the case, I just tried an older forked version of Revadikes repository from lingsamuel https://github.com/lingsamuel/epicgames-freebies-claimer and it worked just fine (both locally and through github actions), I think Revadike changed something in the 2FA portion of the code on his repository that made it stop working correctly or something.

**Comment by JourneyOver** [comment] 2020-06-17 23:22
@maximousblk I figured out why Revadikes repo doesn't get passed the 2FA portion, he missed something completely obvious in the code. On line 59 in claimer.js in his repository it is
```
if (!await client.login().catch(() => false)) {
```

while it actually should be
```
if (!await client.login(account).catch(() => false)) {
```

upon changing it, it passes the 2FA just fine on my testings.

**Comment by maximousblk** [comment] 2020-06-18 08:06
@JourneyOver that is genius!

I was having a hard time figuring out why this was the case and you did it in a day.

Thank You

**Comment by maximousblk** [comment] 2020-06-26 10:45
@JourneyOver closing this issue because it is a problem with the main repo

**Closed** 2020-06-26 10:46 UTC
